nelmio_api_doc:
  documentation:
    host: 'localhost:8000'
    schemes: [http]
    info:
      title: Mars Rover API
      description: Mars Rover API Documentation
      version: 1.1.0
  areas:
    default:
      path_patterns:
        - ^/api(?!/doc$)(?!/doc.json$)